sonar.projectKey=sams-big-fake-company_java-remittance
sonar.organization=sams-big-fake-company
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=**/db/migration/**
sonar.cpd.exclusions=**/db/migration/**
