server:
  port: 8080

spring:
  application:
    name: java-remittance
  datasource:
    url: jdbc:h2:mem:remittancedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.bigfake.remittance: INFO
remittance:
  security:
    username: admin
    password: changeit
  matching:
    min-absolute-tolerance: 0.50
    tolerance-percent: 0.5
  inbound:
    directory: ./inbound-remittance
  exceptions:
    stale-after-hours: 24
  scheduling:
    enabled: true
