package com.bigfake.remittance.domain.enums;

public enum RejectReason {
    UNKNOWN_PAYER, INACTIVE_PAYER, INVALID_AMOUNT, INVALID_DATE,
    MISSING_INVOICE_REFERENCE, MISSING_DEDUCTION_CODE, INVALID_DEDUCTION_CODE,
    MALFORMED_RECORD, CONTROL_TOTAL_MISMATCH, MALFORMED_STRUCTURE, DUPLICATE_FILE
}
