CREATE TABLE open_invoice (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payer_code VARCHAR(20) NOT NULL,
 invoice_reference VARCHAR(100) NOT NULL, normalized_reference VARCHAR(100) NOT NULL,
 invoiced_amount NUMERIC(19,2) NOT NULL, outstanding_amount NUMERIC(19,2) NOT NULL,
 due_date DATE, status VARCHAR(30) NOT NULL, created_at TIMESTAMP, created_by VARCHAR(100),
 updated_at TIMESTAMP, updated_by VARCHAR(100), version BIGINT, is_enabled CHAR(1) DEFAULT 'Y'
);
CREATE INDEX idx_invoice_payer_amount ON open_invoice(payer_code, outstanding_amount);
CREATE INDEX idx_invoice_normalized_reference ON open_invoice(normalized_reference);
CREATE TABLE remittance_advice (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, advice_number VARCHAR(50) NOT NULL UNIQUE,
 remittance_file_id BIGINT NOT NULL, payer_code VARCHAR(20) NOT NULL, remittance_date DATE NOT NULL,
 total_paid_amount NUMERIC(19,2) NOT NULL, line_count BIGINT NOT NULL, status VARCHAR(30) NOT NULL,
 created_at TIMESTAMP, created_by VARCHAR(100), updated_at TIMESTAMP, updated_by VARCHAR(100), version BIGINT, is_enabled CHAR(1) DEFAULT 'Y',
 CONSTRAINT fk_advice_file FOREIGN KEY (remittance_file_id) REFERENCES remittance_file(id)
);
CREATE TABLE payment_instruction (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instruction_reference VARCHAR(60) NOT NULL UNIQUE,
 remittance_advice_id BIGINT NOT NULL, payer_code VARCHAR(20) NOT NULL, amount NUMERIC(19,2) NOT NULL,
 status VARCHAR(30) NOT NULL, sent_at TIMESTAMP, failure_reason VARCHAR(500),
 created_at TIMESTAMP, created_by VARCHAR(100), updated_at TIMESTAMP, updated_by VARCHAR(100), version BIGINT, is_enabled CHAR(1) DEFAULT 'Y',
 CONSTRAINT fk_instruction_advice FOREIGN KEY (remittance_advice_id) REFERENCES remittance_advice(id)
);
